import {
  InterviewStat,
  InterviewDetail,
} from "../interfaces/interview.interface";

export const statusStyles = {
  scheduled: "bg-[#e0f2fe] text-[#0369a1] border-transparent",
  "in-progress": "bg-[#fef3c7] text-[#d97706] border-transparent",
  completed: "bg-[#def2eb] text-[#0e4230] border-transparent",
  cancelled: "bg-[#fcefec] text-[#d92d20] border-transparent",
};

// Mock interview data
export const mockInterviews: InterviewDetail[] = [
  {
    id: "1",
    interviewId: "int-001",
    candidateName: "John Doe",
    candidateEmail: "john.doe@example.com",
    jobTitle: "Senior Frontend Developer",
    jobId: "job-001",
    interviewerName: "AI Interviewer - Sarah",
    interviewerId: "ai-001",
    status: "Scheduled",
    scheduledDate: "2024-01-20",
    scheduledTime: "14:00",
    duration: 45,
    roundName: "Technical Screening",
    roundId: "round-001",
    score: undefined,
    completedAt: undefined,
    createdAt: "2d ago",
    updatedAt: "2d ago",
    interviewLink: "/interviews/token-001/instructions",
    token: "token-001",
  },
  {
    id: "2",
    interviewId: "int-002",
    candidateName: "Jane Smith",
    candidateEmail: "jane.smith@example.com",
    jobTitle: "Product Manager",
    jobId: "job-002",
    interviewerName: "AI Interviewer - Michael",
    interviewerId: "ai-002",
    status: "in-progress",
    scheduledDate: "2024-01-18",
    scheduledTime: "10:30",
    duration: 60,
    roundName: "Behavioral Round",
    roundId: "round-002",
    score: undefined,
    completedAt: undefined,
    createdAt: "3d ago",
    updatedAt: "1h ago",
    interviewLink: "/interviews/token-002/instructions",
    token: "token-002",
  },
  {
    id: "3",
    interviewId: "int-003",
    candidateName: "Robert Johnson",
    candidateEmail: "robert.j@example.com",
    jobTitle: "UX Designer",
    jobId: "job-003",
    interviewerName: "AI Interviewer - Emily",
    interviewerId: "ai-003",
    status: "completed",
    scheduledDate: "2024-01-15",
    scheduledTime: "15:00",
    duration: 30,
    roundName: "Portfolio Review",
    roundId: "round-003",
    score: 88,
    completedAt: "2024-01-15T15:30:00Z",
    createdAt: "5d ago",
    updatedAt: "5d ago",
    interviewLink: "/interviews/token-003/instructions",
    token: "token-003",
  },
  {
    id: "4",
    interviewId: "int-004",
    candidateName: "Emily Davis",
    candidateEmail: "emily.davis@example.com",
    jobTitle: "Senior Frontend Developer",
    jobId: "job-001",
    interviewerName: "AI Interviewer - Sarah",
    interviewerId: "ai-001",
    status: "completed",
    scheduledDate: "2024-01-14",
    scheduledTime: "11:00",
    duration: 45,
    roundName: "Technical Screening",
    roundId: "round-001",
    score: 92,
    completedAt: "2024-01-14T11:45:00Z",
    createdAt: "6d ago",
    updatedAt: "6d ago",
    interviewLink: "/interviews/token-004/instructions",
    token: "token-004",
  },
  {
    id: "5",
    interviewId: "int-005",
    candidateName: "Michael Brown",
    candidateEmail: "michael.brown@example.com",
    jobTitle: "Backend Developer",
    jobId: "job-004",
    interviewerName: "AI Interviewer - David",
    interviewerId: "ai-004",
    status: "scheduled",
    scheduledDate: "2024-01-22",
    scheduledTime: "09:00",
    duration: 60,
    roundName: "Technical Deep Dive",
    roundId: "round-004",
    score: undefined,
    completedAt: undefined,
    createdAt: "1d ago",
    updatedAt: "1d ago",
    interviewLink: "/interviews/token-005/instructions",
    token: "token-005",
  },
  {
    id: "6",
    interviewId: "int-006",
    candidateName: "Sarah Wilson",
    candidateEmail: "sarah.wilson@example.com",
    jobTitle: "Product Manager",
    jobId: "job-002",
    interviewerName: "AI Interviewer - Michael",
    interviewerId: "ai-002",
    status: "completed",
    scheduledDate: "2024-01-12",
    scheduledTime: "13:30",
    duration: 60,
    roundName: "Final Round",
    roundId: "round-005",
    score: 85,
    completedAt: "2024-01-12T14:30:00Z",
    createdAt: "8d ago",
    updatedAt: "8d ago",
    interviewLink: "/interviews/token-006/instructions",
    token: "token-006",
  },
  {
    id: "7",
    interviewId: "int-007",
    candidateName: "David Martinez",
    candidateEmail: "david.m@example.com",
    jobTitle: "UX Designer",
    jobId: "job-003",
    interviewerName: "AI Interviewer - Emily",
    interviewerId: "ai-003",
    status: "cancelled",
    scheduledDate: "2024-01-10",
    scheduledTime: "16:00",
    duration: 30,
    roundName: "Portfolio Review",
    roundId: "round-003",
    score: undefined,
    completedAt: undefined,
    createdAt: "10d ago",
    updatedAt: "10d ago",
    interviewLink: "/interviews/token-007/instructions",
    token: "token-007",
  },
  {
    id: "8",
    interviewId: "int-008",
    candidateName: "Lisa Anderson",
    candidateEmail: "lisa.a@example.com",
    jobTitle: "Senior Frontend Developer",
    jobId: "job-001",
    interviewerName: "AI Interviewer - Sarah",
    interviewerId: "ai-001",
    status: "pending",
    scheduledDate: "2024-01-25",
    scheduledTime: "14:00",
    duration: 45,
    roundName: "Technical Screening",
    roundId: "round-001",
    score: undefined,
    completedAt: undefined,
    createdAt: "1h ago",
    updatedAt: "1h ago",
    interviewLink: "/interviews/token-008/instructions",
    token: "token-008",
  },
  {
    id: "9",
    interviewId: "int-009",
    candidateName: "James Taylor",
    candidateEmail: "james.taylor@example.com",
    jobTitle: "Backend Developer",
    jobId: "job-004",
    interviewerName: "AI Interviewer - David",
    interviewerId: "ai-004",
    status: "completed",
    scheduledDate: "2024-01-11",
    scheduledTime: "10:00",
    duration: 60,
    roundName: "Technical Deep Dive",
    roundId: "round-004",
    score: 79,
    completedAt: "2024-01-11T11:00:00Z",
    createdAt: "9d ago",
    updatedAt: "9d ago",
    interviewLink: "/interviews/token-009/instructions",
    token: "token-009",
  },
  {
    id: "10",
    interviewId: "int-010",
    candidateName: "Maria Garcia",
    candidateEmail: "maria.garcia@example.com",
    jobTitle: "Product Manager",
    jobId: "job-002",
    interviewerName: "AI Interviewer - Michael",
    interviewerId: "ai-002",
    status: "scheduled",
    scheduledDate: "2024-01-21",
    scheduledTime: "15:30",
    duration: 60,
    roundName: "Behavioral Round",
    roundId: "round-002",
    score: undefined,
    completedAt: undefined,
    createdAt: "2d ago",
    updatedAt: "2d ago",
    interviewLink: "/interviews/token-010/instructions",
    token: "token-010",
  },
  {
    id: "11",
    interviewId: "int-011",
    candidateName: "Christopher Lee",
    candidateEmail: "chris.lee@example.com",
    jobTitle: "UX Designer",
    jobId: "job-003",
    interviewerName: "AI Interviewer - Emily",
    interviewerId: "ai-003",
    status: "in-progress",
    scheduledDate: "2024-01-19",
    scheduledTime: "11:00",
    duration: 30,
    roundName: "Portfolio Review",
    roundId: "round-003",
    score: undefined,
    completedAt: undefined,
    createdAt: "1d ago",
    updatedAt: "30m ago",
    interviewLink: "/interviews/token-011/instructions",
    token: "token-011",
  },
  {
    id: "12",
    interviewId: "int-012",
    candidateName: "Amanda White",
    candidateEmail: "amanda.white@example.com",
    jobTitle: "Senior Frontend Developer",
    jobId: "job-001",
    interviewerName: "AI Interviewer - Sarah",
    interviewerId: "ai-001",
    status: "completed",
    scheduledDate: "2024-01-13",
    scheduledTime: "09:30",
    duration: 45,
    roundName: "Technical Screening",
    roundId: "round-001",
    score: 91,
    completedAt: "2024-01-13T10:15:00Z",
    createdAt: "7d ago",
    updatedAt: "7d ago",
    interviewLink: "/interviews/token-012/instructions",
    token: "token-012",
  },
];

// Calculate stats from mock data
const calculateStats = (): InterviewStat[] => {
  const total = mockInterviews.length;
  const scheduled = mockInterviews.filter(
    (i) => i.status === "scheduled"
  ).length;
  const completed = mockInterviews.filter(
    (i) => i.status === "completed"
  ).length;
  const completedWithScores = mockInterviews.filter(
    (i) => i.status === "completed" && i.score !== undefined
  );
  const avgScore =
    completedWithScores.length > 0
      ? (
          completedWithScores.reduce((sum, i) => sum + (i.score || 0), 0) /
          completedWithScores.length
        ).toFixed(1)
      : "0";

  return [
    { label: "Total Interviews", value: total, icon: "total" },
    { label: "Scheduled", value: scheduled, icon: "scheduled" },
    { label: "Completed", value: completed, icon: "completed" },
    { label: "Avg. Score", value: avgScore, icon: "score" },
  ];
};

export const stats: InterviewStat[] = calculateStats();
